### ISSUE TITLE
大佬可以分享一下训练用的 config 文件吗

### ISSUE THREAD

**Issue by WoodwindHu** [ylwhxht/SRKD-DRET#1]
我这边跑 baseline 在 DA 数据集上的 eval 结果都很差诶，可以分享一下训练用的 config 文件吗，方便我查一下问题出在哪

**Comment by ylwhxht** [comment]
> 我这边跑 baseline 在 DA 数据集上的 eval 结果都很差诶，可以分享一下训练用的 config 文件吗，方便我查一下问题出在哪

我们并不是使用DA数据集的eval结果，上面包含了各种复杂条件，而是DA数据集中挑选的几十个典型雨天序列。
DA数据集上不同序列精度波动比较厉害，如果你使用完整的DA数据集是很有可能偏低。我认为你先在waymo经典数据集上验证结果，即可知道训练是否有问题。我们对训练config基本没有做什么修改，如果你有需要也可以提供。

**Comment by WoodwindHu** [comment]
那可以分享一下你们跳出来的序列的列表吗



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Xun Huang ***@***.***&gt;
发送时间: 2024年5月5日 10:59
收件人: ylwhxht/SRKD-DRET ***@***.***&gt;
抄送: 胡黔江 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [ylwhxht/SRKD-DRET] 大佬可以分享一下训练用的 config 文件吗 (Issue #1)





  
我这边跑 baseline 在 DA 数据集上的 eval 结果都很差诶，可以分享一下训练用的 config 文件吗，方便我查一下问题出在哪
  
我们并不是使用DA数据集的eval结果，上面包含了各种复杂条件，而是DA数据集中挑选的几十个典型雨天序列。
 DA数据集上不同序列精度波动比较厉害，如果你使用完整的DA数据集是很有可能偏低。我认为你先在waymo经典数据集上验证结果，即可知道训练是否有问题。我们对训练config基本没有做什么修改，如果你有需要也可以提供。

**Comment by ylwhxht** [comment]
> 那可以分享一下你们挑出来的序列的列表吗
> […](#)

Ok，但是不好意思。我现在不在学校，等回去了找下imageset。如果你比较急的话，在这之前你可以先验证在传统waymo的结果。

**Comment by WoodwindHu** [comment]
好的，谢谢～
你们当时挑这些序列的时候是根据什么呀，我这边看 tfrecord 里面标注的 weather 都是 unknown，根本用不了

**Comment by ylwhxht** [comment]
> 好的，谢谢～
> 你们当时挑这些序列的时候是根据什么呀，我这边看 tfrecord 里面标注的 weather 都是 unknown，根本用不了

对的，标注确实是unknown。
所以我们是根据每个序列前几帧点云场景可视化与图像人工筛选判断的，会有一些主观成分。
如果不是专门聚焦雨天的话，用全部的就可以。
可以参考SPG: Unsupervised Domain Adaptation for 3D Object Detection via Semantic Point Generation。

**Comment by WoodwindHu** [comment]
你好，imageset大概什么时候更新在代码里呀

**Comment by ylwhxht** [comment]
> 你好，imageset大概什么时候更新在代码里呀

不好意思，最近在赶ddl有点忙忘了。
应该是下面这些，后续我再整合到repo中。
segment-352996830797845126_547_000_567_000.tfrecord
segment-10495858009395654700_197_000_217_000.tfrecord
segment-11686124028837937738_3660_000_3680_000.tfrecord
segment-11876826095957896433_2300_000_2320_000.tfrecord
segment-13251487330618725542_423_000_443_000.tfrecord
segment-14262528452308149004_549_000_569_000.tfrecord
segment-14440967969245082489_574_000_594_000.tfrecord
segment-1688924041054198124_599_000_619_000.tfrecord
segment-18335655790141497353_524_000_544_000.tfrecord
segment-3287735319864139367_647_000_667_000.tfrecord
segment-4301691834048231550_522_000_542_000.tfrecord
segment-8512529767771141103_924_000_944_000.tfrecord
segment-9330535161582170634_453_000_473_000.tfrecord
segment-9622335770432948456_2680_000_2700_000.tfrecord

**Comment by WoodwindHu** [comment]
好的，谢谢
